name: 'employee_db'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'employee_db'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

dbt-cloud: 
    project-id: workato-employee-db-425013

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  employee_db:
    +schema: public

# Configuring seeds
# Full documentation: https://docs.getdbt.com/docs/building-a-dbt-project/seeds
seeds:
  employee_db:
    +schema: public